## Video 2

In [2]:
arr = [1,2,3]
print(arr*5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
import numpy as np

arr = np.array([1,2,3])
print(arr*5)

[ 5 10 15]


### Nd array

In [4]:
import numpy as np

#1D array
arr1 = np.array([1,2,3])

print(type(arr1))
print(arr1.ndim)

#2D array
arr2 = np.array([
    [1,2,3], #row
    [4,5,6] # col
])

print(arr2.ndim)

# 3D array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
    [4,5,6]
    ]
])

<class 'numpy.ndarray'>
1
2


### Attributes

In [5]:
#Dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#Data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(3,)
(2, 3)
(2, 2, 3)
int64
int64
int64
3
6
12


## Video 3

### nd array datatype

In [6]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.4,2.5,3.6])

print(arr.dtype)

int64
float64


In [7]:
#upcasted to float

arr = np.array([1,2,3.5])

print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.5,'5'])

print(arr.dtype)

float64
<U32


#### selecting a data type for a nd array

In [8]:
arr = np.array([1,2,3], dtype=np.int16)
print(arr.dtype)
arr = arr.astype(np.int32)

print(arr.dtype)

int16
int32


## Video 4

#### nd array creation from existing data.

In [9]:
#list
lst = [10,20,30,40,40.5]

arr = np.array(lst,dtype=np.int64)

print(arr)
print(type(arr))
print(arr.dtype)

mixed_list = [19,13.5,True,"hello"]

arr = np.array(mixed_list)
# arr = np.array(mixed_list,dtype=np.int64) #error

print(arr)
print(type(arr))
print(arr.dtype)

matrix = np.array([
    [1,2,3], #row
    [4,5,6] # col
])

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[10 20 30 40 40]
<class 'numpy.ndarray'>
int64
['19' '13.5' 'True' 'hello']
<class 'numpy.ndarray'>
<U32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [10]:
#tuple
tpl = (1,3,5,6)

arr = np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 3 5 6]
<class 'numpy.ndarray'>
int64
(4,)
1


In [11]:
#set
st = {1,2,3}
#we can't pass set directly like list and tuple we have to convert in list then pass in nd array.
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [12]:
#dictionary
dc = {
    "a":10,
    "b":20,
    "c":30
}

keys = dc.keys()
values = dc.values()
items = dc.items()

print(keys)
print(values)
print(items)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [13]:
# keys to nd array
arr = np.array(list(keys))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1


In [14]:
# values to nd array
arr = np.array(list(values))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1


In [15]:
# items to nd array
arr = np.array(list(items))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2


## Video 5

#### nd array creation from scratch

In [17]:
#np array zeros

arr = np.zeros((1,5))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(1, 5)
2
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)


In [18]:
#np array ones

arr = np.ones((1,5))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr = np.ones_like(arr3)
print(arr)
print(arr.shape)

[[1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(1, 5)
2
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [27]:
#np array empty

arr = np.empty((1,5))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(1, 5)
2
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [28]:
#np array full

arr = np.full((1,5),7)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr = np.full_like(arr3,30)
print(arr)
print(arr.shape)

[[7 7 7 7 7]]
<class 'numpy.ndarray'>
int64
(1, 5)
2
[[[30 30 30]
  [30 30 30]]

 [[30 30 30]
  [30 30 30]]]
(2, 2, 3)
