In [1]:
import numpy as np

print(np.sin(np.pi/2))

1.0


In [3]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])
mat = np.dot(A,B)
print(mat)

[[19 22]
 [43 50]]


<img src="./practice_problem1.png"/>

In [1]:
import numpy as np
celsius = [0, 20, 40, 60, 100]

cel = np.array(celsius)
fahrenheit = cel * 9 / 5 + 32
print(fahrenheit)



[ 32.  68. 104. 140. 212.]


<img src="./practice_problem2.png"/>

In [7]:
lap_time_list = [80, 75, 90, 85, 95, 100, 110, 120, 130, 140]
lap_time = np.array(lap_time_list)
print(lap_time)
print(lap_time.shape)
print(lap_time.size)
print(lap_time.dtype)

time_in_minutes = lap_time/60
print(np.round(time_in_minutes, 2))

[ 80  75  90  85  95 100 110 120 130 140]
(10,)
10
int64
[1.33 1.25 1.5  1.42 1.58 1.67 1.83 2.   2.17 2.33]
