### 1. Student Marks Analyzer
You are helping a teacher check exam results.
 Create a NumPy array with 10 random integers between 0 and 100 (student scores).

 Find:
 - the highest score
 - the lowest score
 - the average score

 Hint: use np.random.randint(), arr.max(), arr.min(), arr.mean()

In [12]:
import numpy as np

results = np.random.randint(0, 100, size=10)
print(results)
highest_score = np.max(results)
print("Highest score:", highest_score)
lowest_score = np.min(results)
print("Lowest score:", lowest_score)
avg_score = np.mean(results)
print("Average score:", avg_score)

[68 32 24 72 65 62 61 49 12 82]
Highest score: 82
Lowest score: 12
Average score: 52.7


### 2. Warehouse Weights
A warehouse stores item weights (in kg):
 arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

 Find and print:
 - all items heavier than 50 kg
 - the sorted weights
 - the index of the heaviest item

 Hint: use arr[arr > 50], np.sort(arr), arr.argmax()

In [13]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

weights_over_fifty = arr[arr>50]
print("All items heavier then 50 :",weights_over_fifty)
sorted_weight =np.sort(arr)
heaviest_item_index = arr.argmax()
print("Sorted Weight :",sorted_weight)
print("The index of heaviest item :",heaviest_item_index)

All items heavier then 50 : [60 55 90 75]
Sorted Weight : [30 40 45 50 55 60 75 90]
The index of heaviest item : 4


### 3. Temperature Report
A weather station collects temperatures (°C) from 4 zones.
 Generate random integers between 20 and 40 for a 4×4 grid.

 Then find:
 - the average temperature of each zone (row)
 - the highest temperature in the grid
 - replace all temperatures above 35 with 35


In [14]:
temperatures = np.random.randint(20,40,size=16).reshape(4,4)
print(temperatures)
print(np.mean(temperatures[3:4]))
each_zone_avg = np.mean(temperatures, axis =1)
print(each_zone_avg)
highest_temp = np.max(temperatures)
print("Highest temperature recorded :",highest_temp)
temperatures[temperatures > 35] = 35
print(temperatures)

[[29 21 25 21]
 [37 31 32 24]
 [24 39 35 35]
 [31 31 23 38]]
30.75
[24.   31.   33.25 30.75]
Highest temperature recorded : 39
[[29 21 25 21]
 [35 31 32 24]
 [24 35 35 35]
 [31 31 23 35]]


### 4. Traffic Data
A city records the number of cars passing 5 intersections in 3 time slots (morning, afternoon, night).
 Create a 3×5 array of random integers between 0 and 50.

 Then find:
 - total cars per intersection (sum by column)
 - total cars per time slot (sum by row)


In [15]:
slots = np.random.randint(0,50,15).reshape(3,5)
print(slots)
total_intersection = np.sum(slots, axis=0)
total_slot = np.sum(slots, axis=1)
print("Total items in each slot :",total_slot)
print("Total items in each intersection :",total_intersection)

[[41 34 10 10 20]
 [ 8 28 15  3  6]
 [ 5 33 44  9 30]]
Total items in each slot : [115  60 121]
Total items in each intersection : [54 95 69 22 56]


### 5. Fruit Store Stock
You sell fruits in your store. Stock levels (kg) for 5 days are:
 stock = np.array([12, 15, 9, 20, 18])

 A new delivery adds 5 kg to each stock.
 Then 10% of all fruits get spoiled.

 Find the final stock levels.

 Hint: use broadcasting and simple math.