<img src="./problem1.png">

In [2]:
import numpy as np
list_1D = [5,3,5,2,8,1,9,3,4,7]
array_1D = np.array(list_1D)
print(array_1D)
print(array_1D.shape)
print(array_1D.size)
print(array_1D.dtype)
print(array_1D.ndim)

list_2D = [[5,3,5,2,8],[1,9,3,4,7]]
array_2D =  np.array(list_2D)
print(array_2D)
print(array_2D.shape)
print(array_2D.size)
print(array_2D.dtype)
print(array_2D.ndim)

list_3D = [[[5,3,5],[2,8,1]],[[9,3,4],[7,6,2]]]
array_3D = np.array(list_3D)
print(array_3D)
print(array_3D.shape)
print(array_3D.size)
print(array_3D.dtype)
print(array_3D.ndim)    

[5 3 5 2 8 1 9 3 4 7]
(10,)
10
int64
1
[[5 3 5 2 8]
 [1 9 3 4 7]]
(2, 5)
10
int64
2
[[[5 3 5]
  [2 8 1]]

 [[9 3 4]
  [7 6 2]]]
(2, 2, 3)
12
int64
3


<img src="./problem2.png">

In [3]:
array_of_zeros = np.zeros((3,3))
print(array_of_zeros)
print(array_of_zeros.shape)
print(array_of_zeros.size)
print(array_of_zeros.dtype)
print(array_of_zeros.ndim)
array_of_ones = np.ones((2,5))
print(array_of_ones)
print(array_of_ones.shape)
print(array_of_ones.size)
print(array_of_ones.dtype)
print(array_of_ones.ndim)   
array_of_seven = np.full((4,4),7)
print(array_of_seven)
print(array_of_seven.shape)
print(array_of_seven.size)
print(array_of_seven.dtype)
print(array_of_seven.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9
float64
2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
10
float64
2
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
(4, 4)
16
int64
2


<img src="./problem3.png">

In [4]:
even_num_array = np.arange(10,50,2)
print(even_num_array)
print(even_num_array.shape)
print(even_num_array.size)
print(even_num_array.dtype)
print(even_num_array.ndim)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
(20,)
20
int64
1


<img src="./problem4.png">

In [7]:
mat = np.linspace(0,15,16).reshape(4,4)
print(mat)
first_row = mat[0,:]
print("First Row:",first_row)
last_column = mat[:,3]
print("Last Column:",last_column)
sub_matrix = mat[1:3,1:3]
print("Sub Matrix:\n",sub_matrix)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
First Row: [0. 1. 2. 3.]
Last Column: [ 3.  7. 11. 15.]
Sub Matrix:
 [[ 5.  6.]
 [ 9. 10.]]


<img src="./problem5.png">

In [9]:
lst = [1,2,3]
arr = np.array(lst)

mat = np.linspace(1,9,9).reshape(3,3)
print(mat)

sum_mat = mat+arr
print(sum_mat)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  4.  6.]
 [ 5.  7.  9.]
 [ 8. 10. 12.]]


<img src="./problem6.png">

In [22]:
A = np.random.randint(1,10,size=(7))
B = np.random.randint(1,10,size=(7))
print(A)
print(B)
equ1 = (A+B)/2
equ2 = A**2 + B**2
print("Equation 1 Result:",equ1)
print("Equation 2 Result:",equ2)

[6 4 7 6 4 9 6]
[9 1 8 6 9 5 6]
Equation 1 Result: [7.5 2.5 7.5 6.  6.5 7.  6. ]
Equation 2 Result: [117  17 113  72  97 106  72]
