## **Email address: asif.ikbal662@gmail.com**

In [14]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# Numpy Quesionts

### Answer to the Q1

In [15]:
#Q1. Create NumPy arrays from the ages and salaries data generated above.
#Print both arrays and display their dtype, ndim, shape, and size.
# print(ages)
# print(salaries)
# print(type(ages))
# print(type(salaries))
ages_arr = np.array(ages)
salaries_arr = np.array(salaries)

print(ages_arr)
print(type(ages_arr))
print(ages_arr.dtype)
print(ages_arr.ndim)
print(ages_arr.shape)
print(ages_arr.size)
print("-------------------")
print(salaries_arr)
print(type(salaries_arr))
print(salaries_arr.dtype)
print(salaries_arr.ndim)
print(salaries_arr.shape)
print(salaries_arr.size)


[56 46 32 25 38 56 36 40 28 28]
<class 'numpy.ndarray'>
int64
1
(10,)
10
-------------------
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
<class 'numpy.ndarray'>
int64
1
(10,)
10


### Answer to the Q2

In [16]:
#Q2. Using the salaries array, find and print the highest and lowest salary values.
#Also, calculate and print the average salary and age using NumPy functions.
print(salaries.max())
print(salaries.min())
print(salaries.mean())
print(ages.mean())
#

89735
30769
57446.9
38.5


### Answer to the Q3

In [17]:
#Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition.
#Then count and print how many employees are older than 30.
print(ages[ages>30])
print(ages[ages>30].size)


[56 46 32 38 56 36 40]
7


### Answer to the Q4

In [18]:
#Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array).
#Print the new updated ages array.
ages_five_plus = ages + 5

# print(ages)
print(ages_five_plus)

[61 51 37 30 43 61 41 45 33 33]


### Answer to the Q5

In [19]:
#Q5. Using NumPy,
#calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary.
#Print both results.
total_salary = salaries.sum()
highest_salary = salaries.max()
lowest_salary = salaries.min()
salaries_diff = highest_salary - lowest_salary
print(total_salary)
print(salaries_diff)

574469
58966


# Pandas Question Problem

### Answer to the Q6

In [20]:
#Q6. Load the employees.csv file into a Pandas DataFrame.
#Display the first 5 rows, and check basic info using info() and summary statistics using describe().
df = pd.read_csv("./employees.csv")
print(df.head())

df.info()

df.describe()

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

### Answer to the Q7

In [21]:
#Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().
print(df[["id","age","salary"]])
print("--------------")
print(df.tail(3))


   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311
--------------
   id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR


### Answer to the Q8

In [22]:
#Q8. Filter the DataFrame to show only employees who work in the IT department.
#Print the result and show the total number of IT employees.
it_dept = df[df["dept"]=="IT"]
print(it_dept)
print("the total number of IT department employees is ",len(it_dept.index))


   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
the total number of IT department employees is  3


### Answer to the Q9

In [23]:
#Q9. Sort the DataFrame by salary in descending order and
#display the top 3 highest-paid employees along with their department and age.
sorted_df = df.sort_values("salary",ascending=False)
print(sorted_df.head(3))

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR


### Answer to the Q10

In [24]:
#Q10. Replace all salary values greater than 80000 with 80000 using loc.
#Then calculate and print the new average salary of all employees after replacement.
df.loc[df["salary"]>80000,"salary"] = 80000
print(df["salary"].mean())
#

55863.3
