<img src="./practice_problem.png">

In [2]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    a = np.array(a)
    b = np.transpose(a)
    return b

print(transpose_matrix([
    [1, 2, 3],
    [4, 5, 6],
    ]))
print(transpose_matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]))

[[1 4]
 [2 5]
 [3 6]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
